name = "telegram-bot"
main = "src/index.ts"
compatibility_date = "2023-12-01"

[placement]
mode = "smart"
type = "module"

[vars]


[[kv_namespaces]]
id = "e24d480067f14571b4a1dbe1837073be"
binding = "TELEGRAM_BOT_KV"

[observability.logs]
enabled = true